### ISSUE TITLE
REPORTE DE APP CON REALIDAD AUMENTADA_Edwin, Alexis, Iván, Taoli 

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Edwin-1012#2]
[REPORTE DE APP CON REALIDAD AUMENTADA_Edwin, Alexis, Iván, Taoli.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Edwin-1012/files/8103474/REPORTE.DE.APP.CON.REALIDAD.AUMENTADA_Edwin.Alexis.Ivan.Taoli.pdf)

**Comment by Anthony4523** [comment]
Excelente trabajo, contiene todos los datos necesarios que marca la rúbrica y la información está organizada.
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
